title: The Blog of the Century
author: Putu Suabawa
email: myemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This the best blog ever written by a human being. It is so awesome, even Donald Trump will be impressed 
  by the style and the use of superlative words in every corner and turn of the blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
